import pyautogui
import time
from datetime import datetime
pyautogui.FAILSAFE = True
pyautogui.PAUSE = 1
print("Starting Daily Report Bot...")
print(f"Current Time: {datetime.now()}")
print("Step 1: Open chrome browser")
time.sleep(3)
pyautogui.press('win')
time.sleep(3)
pyautogui.typewrite('chrome',interval=0.15)
time.sleep(3)
pyautogui.press('enter')
time.sleep(3)
print("Step 2: Open the weather site")
time.sleep(3)
pyautogui.hotkey('ctrl', 't',interval=0.1)
pyautogui.typewrite('https://www.accuweather.com/en/in/chennai/206671/weather-forecast/206671',interval=0.15)
time.sleep(1)
pyautogui.press('enter')
print("Step 3: Copy all the data from the website")
pyautogui.hotkey('ctrl', 'a',interval=0.3)
time.sleep(1)
pyautogui.hotkey('ctrl', 'c',interval=0.3)
time.sleep(3)
print("Step 4: Open excel sheet and open blank workbook")
time.sleep(8)
pyautogui.press('win')
pyautogui.typewrite('excel',interval=0.15)
pyautogui.press('enter')
time.sleep(3)
print("Step 5: Paste the data into the excel sheet")
time.sleep(3)
pyautogui.hotkey('ctrl', 'v',interval=0.3)
print("Step 6: Save the excel sheet with the current date")
time.sleep(3)
pyautogui.hotkey('ctrl', 's',interval=0.3)
time.sleep(3)
pyautogui.typewrite(f"C:\\Users\\Nisha\\GenAI Program\\venv\\weather_{datetime.now().strftime('%Y-%m-%d')}.xlsx", interval=0.15)
pyautogui.press('enter')
print("Step 7: Take the screenshot of the excel sheet and save it with the current date")
time.sleep(3)
pyautogui.screenshot(f"weather_{datetime.now().strftime('%Y-%m-%d')}.png")
print(" Daily Report Bot completed successfully!")